import type { Subscription } from "@shared/schema";

// ============================================================================
// MOCK SUBSCRIPTIONS DATA
// ============================================================================

export const mockSubscriptions: Subscription[] = [
  {
    id: 1,
    userId: "demo-user",
    merchantName: "Netflix",
    planName: "Premium",
    amount: "15.99",
    currency: "USD",
    billingCycle: "monthly",
    category: "entertainment",
    logoUrl: null,
    logoFetchedAt: null,
    firstBillingDate: new Date("2024-01-15"),
    nextBillingDate: new Date("2025-12-15"),
    trialEndDate: null,
    status: "active",
    cancelledDate: null,
    accessEndsDate: null,
    cancellationUrl: "https://netflix.com/cancelplan",
    notes: null,
    isManualEntry: false,
    confidence: "high",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: 2,
    userId: "demo-user",
    merchantName: "Spotify",
    planName: "Individual",
    amount: "10.99",
    currency: "USD",
    billingCycle: "monthly",
    category: "entertainment",
    logoUrl: null,
    logoFetchedAt: null,
    firstBillingDate: new Date("2024-02-01"),
    nextBillingDate: new Date("2025-12-01"),
    trialEndDate: null,
    status: "active",
    cancelledDate: null,
    accessEndsDate: null,
    cancellationUrl: "https://spotify.com/account",
    notes: null,
    isManualEntry: false,
    confidence: "high",
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-01"),
  },
  {
    id: 3,
    userId: "demo-user",
    merchantName: "ChatGPT",
    planName: "Plus",
    amount: "20.00",
    currency: "USD",
    billingCycle: "monthly",
    category: "ai_tools",
    logoUrl: null,
    logoFetchedAt: null,
    firstBillingDate: new Date("2024-03-10"),
    nextBillingDate: new Date("2025-12-10"),
    trialEndDate: null,
    status: "active",
    cancelledDate: null,
    accessEndsDate: null,
    cancellationUrl: "https://chat.openai.com/settings",
    notes: "Using for AI assistance and coding",
    isManualEntry: true,
    confidence: "high",
    createdAt: new Date("2024-03-10"),
    updatedAt: new Date("2024-03-10"),
  },
  {
    id: 4,
    userId: "demo-user",
    merchantName: "Figma",
    planName: "Professional",
    amount: "12.00",
    currency: "USD",
    billingCycle: "monthly",
    category: "design",
    logoUrl: null,
    logoFetchedAt: null,
    firstBillingDate: new Date("2024-04-05"),
    nextBillingDate: new Date("2025-12-05"),
    trialEndDate: null,
    status: "active",
    cancelledDate: null,
    accessEndsDate: null,
    cancellationUrl: null,
    notes: null,
    isManualEntry: false,
    confidence: "high",
    createdAt: new Date("2024-04-05"),
    updatedAt: new Date("2024-04-05"),
  },
  {
    id: 5,
    userId: "demo-user",
    merchantName: "GitHub",
    planName: "Pro",
    amount: "4.00",
    currency: "USD",
    billingCycle: "monthly",
    category: "development",
    logoUrl: null,
    logoFetchedAt: null,
    firstBillingDate: new Date("2024-01-01"),
    nextBillingDate: new Date("2025-12-01"),
    trialEndDate: null,
    status: "active",
    cancelledDate: null,
    accessEndsDate: null,
    cancellationUrl: "https://github.com/settings/billing",
    notes: null,
    isManualEntry: false,
    confidence: "high",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: 6,
    userId: "demo-user",
    merchantName: "Notion",
    planName: "Plus",
    amount: "10.00",
    currency: "USD",
    billingCycle: "monthly",
    category: "productivity",
    logoUrl: null,
    logoFetchedAt: null,
    firstBillingDate: new Date("2024-05-20"),
    nextBillingDate: new Date("2025-12-20"),
    trialEndDate: null,
    status: "active",
    cancelledDate: null,
    accessEndsDate: null,
    cancellationUrl: null,
    notes: null,
    isManualEntry: false,
    confidence: "medium",
    createdAt: new Date("2024-05-20"),
    updatedAt: new Date("2024-05-20"),
  },
  {
    id: 7,
    userId: "demo-user",
    merchantName: "Adobe Creative Cloud",
    planName: "All Apps",
    amount: "54.99",
    currency: "USD",
    billingCycle: "monthly",
    category: "design",
    logoUrl: null,
    logoFetchedAt: null,
    firstBillingDate: new Date("2024-06-01"),
    nextBillingDate: null,
    trialEndDate: null,
    status: "cancelled",
    cancelledDate: new Date("2024-11-01"),
    accessEndsDate: new Date("2024-11-30"),
    cancellationUrl: null,
    notes: "Cancelled - too expensive, using Figma instead",
    isManualEntry: false,
    confidence: "high",
    createdAt: new Date("2024-06-01"),
    updatedAt: new Date("2024-11-01"),
  },
  {
    id: 8,
    userId: "demo-user",
    merchantName: "Midjourney",
    planName: "Standard",
    amount: "30.00",
    currency: "USD",
    billingCycle: "monthly",
    category: "ai_tools",
    logoUrl: null,
    logoFetchedAt: null,
    firstBillingDate: null,
    nextBillingDate: new Date("2025-11-25"),
    trialEndDate: new Date("2025-11-20"),
    status: "trial",
    cancelledDate: null,
    accessEndsDate: null,
    cancellationUrl: null,
    notes: "Free trial - decide by Nov 20",
    isManualEntry: true,
    confidence: "high",
    createdAt: new Date("2024-11-05"),
    updatedAt: new Date("2024-11-05"),
  },
  {
    id: 9,
    userId: "demo-user",
    merchantName: "Vercel",
    planName: "Pro",
    amount: "20.00",
    currency: "USD",
    billingCycle: "monthly",
    category: "development",
    logoUrl: null,
    logoFetchedAt: null,
    firstBillingDate: new Date("2024-07-15"),
    nextBillingDate: new Date("2025-12-15"),
    trialEndDate: null,
    status: "active",
    cancelledDate: null,
    accessEndsDate: null,
    cancellationUrl: "https://vercel.com/account/billing",
    notes: null,
    isManualEntry: false,
    confidence: "high",
    createdAt: new Date("2024-07-15"),
    updatedAt: new Date("2024-07-15"),
  },
  {
    id: 10,
    userId: "demo-user",
    merchantName: "Canva",
    planName: "Pro",
    amount: "12.99",
    currency: "USD",
    billingCycle: "monthly",
    category: "design",
    logoUrl: null,
    logoFetchedAt: null,
    firstBillingDate: null,
    nextBillingDate: new Date("2025-11-18"),
    trialEndDate: new Date("2025-11-15"),
    status: "trial",
    cancelledDate: null,
    accessEndsDate: null,
    cancellationUrl: null,
    notes: "Testing for social media graphics",
    isManualEntry: false,
    confidence: "medium",
    createdAt: new Date("2024-11-01"),
    updatedAt: new Date("2024-11-01"),
  },
];

// ============================================================================
// MOCK STATS DATA
// ============================================================================

export const mockStats = {
  totalSubscriptions: 8, // Active + Trial
  totalMonthlyCost: "158.97",
  totalAnnualCost: "1907.64",
  byCategory: {
    entertainment: 2,
    ai_tools: 2,
    design: 2,
    development: 2,
    productivity: 1,
  },
  byStatus: {
    active: 6,
    trial: 2,
    cancelled: 1,
    paused: 0,
  },
};

// ============================================================================
// MOCK GMAIL STATUS
// ============================================================================

export const mockGmailStatus = {
  connected: true,
  lastScan: new Date("2025-11-08T10:30:00").toISOString(),
};
